version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SERVERURL=1.1.1.1 #ponga aquí la ip del servidor host de la vpn
      - SERVERPORT=51820
      - PEERS=4 #puede reducir o aumentar la cantidad de licenncias, se puede acceder mediante codigo QR
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - ./wireguard/config:/config #el archivo config contienne los codigo QR
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
